Today's topics:
* `pandas` and `pd.read_csv`
* `DataFrame` and `Series` anatomy
* `.head()`, `.describe()`, and missing data (`NaN`)
* selecting columns and rows: `[]`, `.loc`, `.iloc`

> By the end of today you should be able to complete Problems 1-3 of Homework 3

# From dictionaries to tables

Hand-built dict-of-lists worked for 4 elements, 3 properties.

*What about 52 elements and 19 properties?*

Real datasets live in **files** — `.csv`, downloaded, shared. [pandas](https://pandas.pydata.org/) reads one straight in: `pd.read_csv`.

# Reading a file with `pandas`

`import pandas as pd` — same convention as `np`:

In [1]:
import pandas as pd

52 chemical elements, 19 property columns. [`pd.read_csv`](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html):

## Dataset: Elemental Properties

This dataset contains physical and electronic properties of chemical elements,
including atomic mass, ionization energies, vacancy formation energies,
bulk static energies, and crystal structures.

Note that some entries contain `NaN` (Not a Number) values where data was
unavailable. We'll need to handle these when performing calculations.

In [2]:
import os
import pandas as pd

_file = 'elements.csv'
_github = f'https://raw.githubusercontent.com/wfreinhart/matse219/main/datasets/{_file}'
_local = next(
    (p for p in (f'datasets/{_file}', f'../datasets/{_file}', f'../../datasets/{_file}', f'../../../datasets/{_file}')
     if os.path.exists(p)),
    None,
)

try:
    data = pd.read_csv(_local if _local else _github)
except Exception as e:
    raise RuntimeError(
        f"Could not load '{_file}'. If you are in Colab, check your internet "
        f"connection and that the file exists at {_github}"
    ) from e
data

,Symbol,Bulk Static Energy (eV),Reference Energy (eV),Clean Cohesive,Cohesive Energy (eV),Cohesive Energy Per Atom (eV),Atomic Number,Mendeleev Number,Atomic Mass,STP Phase,Natural Crystal Structure,Vacancy Formation Energy (eV),"Vacancy Migration Energy, non-disp (eV)","Vacancy Migration Energy, disp (eV)",Experimental Hvac,Experimental Hmig,Activation Energy (eV),NEBimageVolume,Ionization Energies (eV)
0,Ac,-442.228190,-0.25,1.0,415.09,3.843385,89,48,227.0000,solid,fcc,1.259565,0.460300,0.454340,NaN,NaN,1.719865,4900.00,5.170000
1,Ag,-305.971040,-0.35,1.0,268.38,2.485000,47,71,107.8600,solid,fcc,0.683455,0.695180,0.695030,1.12,0.60,1.378635,1930.00,7.576230
2,Al,-403.993240,-0.23,1.0,379.35,3.512481,13,80,26.9815,solid,fcc,0.607072,0.581350,0.581650,0.68,0.68,1.188422,1779.29,5.985768
3,Ar,-7.404033,-0.05,1.0,1.71,0.015855,18,3,39.9480,gas,fcc,0.049976,0.020634,NaN,NaN,NaN,0.070610,4859.00,15.759610
4,Au,-353.846200,-0.28,1.0,323.28,2.993363,79,70,196.9700,solid,fcc,0.400096,0.548710,0.547920,0.89,0.84,0.948806,1951.89,9.225530
5,Ba,NaN,NaN,0.0,0.00,0.000000,56,14,137.3200,solid,bcc,1.085024,0.000000,NaN,NaN,NaN,1.085024,0.00,5.211664
6,Be,-395.309910,-0.01,1.0,394.12,3.649236,4,77,9.0120,solid,hcp,-0.062697,0.750210,0.750340,NaN,NaN,0.687513,851.00,9.322700
7,Ca,-216.424440,-0.13,1.0,202.14,1.871703,20,16,40.0780,solid,fcc,1.133600,0.470580,NaN,NaN,NaN,1.604180,4554.00,6.113160
8,Cd,NaN,NaN,0.0,0.00,0.000000,48,75,112.4110,solid,hcp,0.302081,0.000000,NaN,0.45,NaN,0.302081,0.00,8.993820
9,Ce,-640.664090,-1.27,1.0,503.70,4.663924,58,32,140.1160,solid,fcc,1.298365,0.544760,NaN,NaN,NaN,1.843125,2818.00,5.538700
10,Co,-746.519270,-1.34,1.0,601.82,5.572443,27,64,58.9332,solid,hcp,1.841825,1.449150,1.448970,1.71,0.98,3.290975,1111.92,7.881010
11,Cu,-402.331380,-0.25,1.0,375.52,3.477061,29,72,63.5460,solid,fcc,1.066309,0.717190,0.717000,1.29,0.78,1.783499,1292.22,7.726380
12,Dy,NaN,NaN,0.0,0.00,0.000000,66,24,162.5000,solid,hcp,1.716888,0.000000,NaN,NaN,NaN,1.716888,0.00,5.938900
13,Er,-167.230630,-0.03,1.0,164.46,1.522812,68,22,167.2600,solid,hcp,1.023558,0.471990,0.469000,NaN,NaN,1.495548,4423.83,6.107700
14,Fe,-880.187030,-2.79,1.0,579.36,5.364450,26,61,55.8450,solid,bcc,2.319890,1.382390,1.382380,1.40,1.26,3.702280,1104.00,7.902400
15,Ga,-324.313210,-0.34,1.0,287.58,2.662737,31,81,69.7230,solid,orc,-0.041690,0.171860,0.176380,NaN,NaN,0.130170,2041.00,5.999301
16,Ge,NaN,NaN,0.0,0.00,0.000000,32,84,72.6300,solid,dia,0.095483,0.000000,NaN,NaN,NaN,0.095483,0.00,7.899430
17,He,-1.212876,0.00,1.0,1.39,0.012893,2,1,4.0026,gas,hcp,0.003964,0.014930,0.015024,NaN,NaN,0.018894,1786.00,24.587387
18,Hf,-1067.307200,-3.36,1.0,704.04,6.518912,72,50,178.4900,solid,hcp,2.088726,0.808000,0.807900,NaN,NaN,2.896726,2404.07,6.825070
19,Ho,-490.922940,-0.25,1.0,463.58,4.292397,67,23,164.9300,solid,hcp,1.736997,0.733500,0.731120,NaN,NaN,2.470497,3335.00,6.021500
20,In,-293.926910,-0.36,1.0,254.78,2.359084,49,79,114.8180,solid,tet,0.278395,0.232580,NaN,NaN,NaN,0.510975,2951.57,5.786360
21,Ir,-956.982600,-1.25,1.0,822.45,7.615282,77,66,192.2170,solid,fcc,1.554390,2.538280,2.538470,NaN,NaN,4.092670,1569.71,8.967020
22,K,-118.358420,-0.30,1.0,85.48,0.791497,19,10,39.0983,solid,bcc,0.339779,0.155950,NaN,NaN,NaN,0.495729,7948.39,4.340663
23,Kr,-5.697164,-0.03,1.0,2.75,0.025422,36,4,83.8000,gas,fcc,0.003975,0.072984,0.070799,NaN,NaN,0.076959,6203.00,13.999610
24,La,-524.896880,-0.45,1.0,476.02,4.407561,57,33,138.9100,solid,hcp,1.438044,0.208870,0.206700,NaN,NaN,1.646914,4007.00,5.576900
25,Li,-205.678890,-0.31,1.0,172.19,1.594369,3,12,6.9410,solid,bcc,0.597416,0.132810,0.130430,NaN,NaN,0.730226,2184.00,5.391719
26,Mg,-165.137730,-0.05,1.0,160.17,1.483087,12,73,24.3050,solid,hcp,0.816857,0.396270,0.395660,NaN,NaN,1.213127,2487.00,7.646235
27,Mn,-980.975780,-5.32,1.0,406.00,3.759279,25,60,54.9380,solid,cub,2.379911,0.654400,0.653740,NaN,NaN,3.034311,1158.00,7.434020
28,Na,NaN,NaN,0.0,0.00,0.000000,11,11,22.9900,solid,fcc,0.384565,0.138730,NaN,NaN,NaN,0.523295,0.00,5.139076
29,Ne,NaN,NaN,0.0,0.00,0.000000,10,2,20.1800,gas,fcc,-0.009215,0.000000,NaN,NaN,NaN,-0.009215,0.00,21.564540
30,Ni,-596.088000,-0.75,1.0,515.46,4.772756,28,67,58.6934,solid,fcc,1.385617,0.945430,0.944610,1.40,1.32,2.331047,1171.41,7.639800
31,Os,-1198.619400,-2.74,1.0,902.99,8.361009,76,63,190.2300,solid,hcp,2.748072,2.729400,2.729400,NaN,NaN,5.477472,1543.17,8.438230
32,Pb,-400.663080,-0.79,1.0,315.63,2.922492,82,82,207.2000,solid,fcc,0.437906,0.707380,NaN,0.57,0.59,1.145286,0.00,7.416630
33,Pd,-559.848390,-1.48,1.0,400.45,3.707836,46,69,106.4200,solid,fcc,1.156599,0.949650,0.948770,1.85,0.91,2.106249,1659.64,8.336900
34,Pt,-654.091290,-0.53,1.0,597.03,5.528100,78,68,195.0840,solid,fcc,0.609199,1.233590,1.236160,1.32,1.37,1.842789,1691.00,8.958800
35,Rb,-103.902930,-0.28,1.0,73.28,0.678507,37,9,85.4700,solid,bcc,0.301446,0.138630,NaN,NaN,NaN,0.440076,9807.00,4.177128
36,Re,-1331.898600,-4.61,1.0,834.51,7.726911,75,58,186.2100,solid,hcp,2.941206,1.809400,1.810500,NaN,NaN,4.750606,1613.00,7.833520
37,Rh,-785.323900,-1.36,1.0,638.18,5.909095,45,65,102.9100,solid,fcc,1.567762,1.787660,1.787330,NaN,NaN,3.355422,1526.10,7.458900
38,Ru,-982.300740,-2.07,1.0,758.36,7.021854,44,62,101.0700,solid,hcp,2.509163,1.849110,1.850640,NaN,NaN,4.358273,1499.00,7.360500
39,Sc,-678.905040,-2.13,1.0,449.34,4.160571,21,19,44.9559,solid,hcp,2.070932,0.594650,0.596250,NaN,NaN,2.665582,2638.00,6.561490
40,Sr,-181.836780,-0.13,1.0,168.14,1.556883,38,15,87.6200,solid,fcc,0.952216,0.447100,NaN,NaN,NaN,1.399316,5912.27,5.694850
41,Ta,-1254.062000,-3.40,1.0,887.14,8.214243,73,52,180.9480,solid,bcc,2.234215,-0.353800,NaN,NaN,NaN,1.880415,2012.00,7.549570
42,Tb,-497.503940,-0.26,1.0,469.89,4.350825,65,26,158.9300,solid,hcp,1.751832,0.707470,0.706770,NaN,NaN,2.459302,3443.00,5.863800
43,Tc,-1105.695500,-3.26,1.0,753.46,6.976476,43,59,98.0000,solid,hcp,2.621579,1.172500,1.172700,NaN,NaN,3.794079,1566.00,7.280000
44,Th,-800.545330,-0.81,1.0,713.46,6.606091,90,47,232.0381,solid,fcc,1.915683,1.248260,NaN,NaN,NaN,3.163943,3463.00,6.306700
45,Ti,-850.352210,-2.27,1.0,605.41,5.605635,22,51,47.8670,solid,hcp,1.949808,0.449470,0.449260,NaN,NaN,2.399278,1863.00,6.828120
46,Tl,NaN,NaN,NaN,0.00,0.000000,81,78,204.3800,solid,hcp,0.370364,0.000000,NaN,NaN,NaN,0.370364,0.00,6.108194
47,V,NaN,NaN,NaN,0.00,0.000000,23,54,50.9415,solid,bcc,-0.037017,0.000000,NaN,NaN,NaN,-0.037017,0.00,6.746190
48,W,NaN,NaN,NaN,0.00,0.000000,74,55,183.8400,solid,bcc,1.665803,0.000000,NaN,NaN,NaN,1.665803,0.00,7.864030
49,Xe,NaN,NaN,NaN,0.00,0.000000,54,5,131.2930,gas,fcc,0.010220,0.000000,NaN,NaN,NaN,0.010220,0.00,12.129840
50,Y,-694.909710,-2.21,NaN,456.47,4.226575,39,25,88.9100,solid,hcp,1.719251,0.670330,NaN,NaN,NaN,2.389581,3493.00,6.217300
51,Zr,-917.772090,-2.27,NaN,672.27,6.224719,40,49,91.2200,solid,hcp,2.019410,0.506990,0.502350,NaN,NaN,2.526400,2512.00,6.633900

* No `print()` needed — Jupyter renders a `DataFrame` as an HTML table
* Row numbers on the left = the **index**
* Column names = the `.csv`'s first row

# Anatomy of a `DataFrame`

*What actually is `data`?*

In [3]:
type(data)

pandas.core.frame.DataFrame

`pandas.core.frame.DataFrame` — dict keys become **column names**, dict values become **columns**, plus a shared row index.

In [4]:
print(data.columns)

Index(['Symbol', 'Bulk Static Energy (eV)', 'Reference Energy (eV)',
       'Clean Cohesive', 'Cohesive Energy (eV)',
       'Cohesive Energy Per Atom (eV)', 'Atomic Number', 'Mendeleev Number',
       'Atomic Mass', 'STP Phase', 'Natural Crystal Structure',
       'Vacancy Formation Energy (eV)',
       'Vacancy Migration Energy, non-disp (eV)',
       'Vacancy Migration Energy, disp (eV)', 'Experimental Hvac',
       'Experimental Hmig', 'Activation Energy (eV)', 'NEBimageVolume',
       'Ionization Energies (eV)'],
      dtype='object')

All 19 column names.

In [5]:
print(data.index)

RangeIndex(start=0, stop=52, step=1)

Row labels — default `0, 1, 2, ..., 51` (`RangeIndex`).

Pull out a single column:

In [6]:
mass = data['Atomic Mass']
print(type(mass))
mass

<class 'pandas.core.series.Series'>

0     227.0000
1     107.8600
2      26.9815
3      39.9480
4     196.9700
5     137.3200
6       9.0120
7      40.0780
8     112.4110
9     140.1160
10     58.9332
11     63.5460
12    162.5000
13    167.2600
14     55.8450
15     69.7230
16     72.6300
17      4.0026
18    178.4900
19    164.9300
20    114.8180
21    192.2170
22     39.0983
23     83.8000
24    138.9100
25      6.9410
26     24.3050
27     54.9380
28     22.9900
29     20.1800
30     58.6934
31    190.2300
32    207.2000
33    106.4200
34    195.0840
35     85.4700
36    186.2100
37    102.9100
38    101.0700
39     44.9559
40     87.6200
41    180.9480
42    158.9300
43     98.0000
44    232.0381
45     47.8670
46    204.3800
47     50.9415
48    183.8400
49    131.2930
50     88.9100
51     91.2200
Name: Atomic Mass, dtype: float64

A **`Series`** — a NumPy `array` with an index and a name stapled on. Unwrap it with `.values`:

In [7]:
print(type(mass.values))
print(mass.values[:5])

<class 'numpy.ndarray'>
[227.     107.86    26.9815  39.948  196.97  ]

Everything you know about `arrays` — indexing, slicing, elementwise math, `.mean()` — still works once unwrapped.

`.shape`, just like `arrays`:

In [8]:
print(data.shape)

(52, 19)

52 rows, 19 columns. `.dtypes`:

In [9]:
print(data.dtypes)

Symbol                                      object
Bulk Static Energy (eV)                    float64
Reference Energy (eV)                      float64
Clean Cohesive                             float64
Cohesive Energy (eV)                       float64
Cohesive Energy Per Atom (eV)              float64
Atomic Number                                int64
Mendeleev Number                             int64
Atomic Mass                                float64
STP Phase                                   object
Natural Crystal Structure                   object
Vacancy Formation Energy (eV)              float64
Vacancy Migration Energy, non-disp (eV)    float64
Vacancy Migration Energy, disp (eV)        float64
Experimental Hvac                          float64
Experimental Hmig                          float64
Activation Energy (eV)                     float64
NEBimageVolume                             float64
Ionization Energies (eV)                   float64
dtype: object

`float64`, `int64`, and `object` (text — `Symbol`, `STP Phase`, `Natural Crystal Structure`).

> **Read more:** [PDSH — Introducing Pandas Objects](https://jakevdp.github.io/PythonDataScienceHandbook/03.01-introducing-pandas-objects.html)

# Peeking at a big table: `.head()` and missing data

52 rows is small — real datasets run thousands. `.head()` shows the first 5:

In [10]:
data.head()

,Symbol,Bulk Static Energy (eV),Reference Energy (eV),Clean Cohesive,Cohesive Energy (eV),Cohesive Energy Per Atom (eV),Atomic Number,Mendeleev Number,Atomic Mass,STP Phase,Natural Crystal Structure,Vacancy Formation Energy (eV),"Vacancy Migration Energy, non-disp (eV)","Vacancy Migration Energy, disp (eV)",Experimental Hvac,Experimental Hmig,Activation Energy (eV),NEBimageVolume,Ionization Energies (eV)
0,Ac,-442.228190,-0.25,1.0,415.09,3.843385,89,48,227.0000,solid,fcc,1.259565,0.460300,0.45434,NaN,NaN,1.719865,4900.00,5.170000
1,Ag,-305.971040,-0.35,1.0,268.38,2.485000,47,71,107.8600,solid,fcc,0.683455,0.695180,0.69503,1.12,0.60,1.378635,1930.00,7.576230
2,Al,-403.993240,-0.23,1.0,379.35,3.512481,13,80,26.9815,solid,fcc,0.607072,0.581350,0.58165,0.68,0.68,1.188422,1779.29,5.985768
3,Ar,-7.404033,-0.05,1.0,1.71,0.015855,18,3,39.9480,gas,fcc,0.049976,0.020634,NaN,NaN,NaN,0.070610,4859.00,15.759610
4,Au,-353.846200,-0.28,1.0,323.28,2.993363,79,70,196.9700,solid,fcc,0.400096,0.548710,0.54792,0.89,0.84,0.948806,1951.89,9.225530

More rows:

In [11]:
data.head(10)

,Symbol,Bulk Static Energy (eV),Reference Energy (eV),Clean Cohesive,Cohesive Energy (eV),Cohesive Energy Per Atom (eV),Atomic Number,Mendeleev Number,Atomic Mass,STP Phase,Natural Crystal Structure,Vacancy Formation Energy (eV),"Vacancy Migration Energy, non-disp (eV)","Vacancy Migration Energy, disp (eV)",Experimental Hvac,Experimental Hmig,Activation Energy (eV),NEBimageVolume,Ionization Energies (eV)
0,Ac,-442.228190,-0.25,1.0,415.09,3.843385,89,48,227.0000,solid,fcc,1.259565,0.460300,0.45434,NaN,NaN,1.719865,4900.00,5.170000
1,Ag,-305.971040,-0.35,1.0,268.38,2.485000,47,71,107.8600,solid,fcc,0.683455,0.695180,0.69503,1.12,0.60,1.378635,1930.00,7.576230
2,Al,-403.993240,-0.23,1.0,379.35,3.512481,13,80,26.9815,solid,fcc,0.607072,0.581350,0.58165,0.68,0.68,1.188422,1779.29,5.985768
3,Ar,-7.404033,-0.05,1.0,1.71,0.015855,18,3,39.9480,gas,fcc,0.049976,0.020634,NaN,NaN,NaN,0.070610,4859.00,15.759610
4,Au,-353.846200,-0.28,1.0,323.28,2.993363,79,70,196.9700,solid,fcc,0.400096,0.548710,0.54792,0.89,0.84,0.948806,1951.89,9.225530
5,Ba,NaN,NaN,0.0,0.00,0.000000,56,14,137.3200,solid,bcc,1.085024,0.000000,NaN,NaN,NaN,1.085024,0.00,5.211664
6,Be,-395.309910,-0.01,1.0,394.12,3.649236,4,77,9.0120,solid,hcp,-0.062697,0.750210,0.75034,NaN,NaN,0.687513,851.00,9.322700
7,Ca,-216.424440,-0.13,1.0,202.14,1.871703,20,16,40.0780,solid,fcc,1.133600,0.470580,NaN,NaN,NaN,1.604180,4554.00,6.113160
8,Cd,NaN,NaN,0.0,0.00,0.000000,48,75,112.4110,solid,hcp,0.302081,0.000000,NaN,0.45,NaN,0.302081,0.00,8.993820
9,Ce,-640.664090,-1.27,1.0,503.70,4.663924,58,32,140.1160,solid,fcc,1.298365,0.544760,NaN,NaN,NaN,1.843125,2818.00,5.538700

Or the end, with `.tail()`:

In [12]:
data.tail(3)

,Symbol,Bulk Static Energy (eV),Reference Energy (eV),Clean Cohesive,Cohesive Energy (eV),Cohesive Energy Per Atom (eV),Atomic Number,Mendeleev Number,Atomic Mass,STP Phase,Natural Crystal Structure,Vacancy Formation Energy (eV),"Vacancy Migration Energy, non-disp (eV)","Vacancy Migration Energy, disp (eV)",Experimental Hvac,Experimental Hmig,Activation Energy (eV),NEBimageVolume,Ionization Energies (eV)
49,Xe,NaN,NaN,NaN,0.00,0.000000,54,5,131.293,gas,fcc,0.010220,0.00000,NaN,NaN,NaN,0.010220,0.0,12.12984
50,Y,-694.90971,-2.21,NaN,456.47,4.226575,39,25,88.910,solid,hcp,1.719251,0.67033,NaN,NaN,NaN,2.389581,3493.0,6.21730
51,Zr,-917.77209,-2.27,NaN,672.27,6.224719,40,49,91.220,solid,hcp,2.019410,0.50699,0.50235,NaN,NaN,2.526400,2512.0,6.63390

`Experimental Hvac` and `Experimental Hmig` — blank cells render as `NaN`.

`NaN` = "Not a Number" — missing data, not a code error. Count it: `.isna()` (True/False per cell) → `.sum()`:

In [13]:
data.isna().sum()

Symbol                                      0
Bulk Static Energy (eV)                    10
Reference Energy (eV)                      10
Clean Cohesive                              6
Cohesive Energy (eV)                        0
Cohesive Energy Per Atom (eV)               0
Atomic Number                               0
Mendeleev Number                            0
Atomic Mass                                 0
STP Phase                                   0
Natural Crystal Structure                   0
Vacancy Formation Energy (eV)               0
Vacancy Migration Energy, non-disp (eV)     0
Vacancy Migration Energy, disp (eV)        21
Experimental Hvac                          41
Experimental Hmig                          42
Activation Energy (eV)                      0
NEBimageVolume                              0
Ionization Energies (eV)                    0
dtype: int64

Most of the 52 elements are missing those two experimental columns.

Fixing missing data (`.dropna()`, `.fillna()`) comes later — today, just recognize `NaN` on sight.

# Selecting columns

*More than one column at once?*

In [14]:
data[['Symbol', 'Atomic Mass']]

   Symbol  Atomic Mass
0      Ac     227.0000
1      Ag     107.8600
2      Al      26.9815
3      Ar      39.9480
4      Au     196.9700
5      Ba     137.3200
6      Be       9.0120
7      Ca      40.0780
8      Cd     112.4110
9      Ce     140.1160
10     Co      58.9332
11     Cu      63.5460
12     Dy     162.5000
13     Er     167.2600
14     Fe      55.8450
15     Ga      69.7230
16     Ge      72.6300
17     He       4.0026
18     Hf     178.4900
19     Ho     164.9300
20     In     114.8180
21     Ir     192.2170
22      K      39.0983
23     Kr      83.8000
24     La     138.9100
25     Li       6.9410
26     Mg      24.3050
27     Mn      54.9380
28     Na      22.9900
29     Ne      20.1800
30     Ni      58.6934
31     Os     190.2300
32     Pb     207.2000
33     Pd     106.4200
34     Pt     195.0840
35     Rb      85.4700
36     Re     186.2100
37     Rh     102.9100
38     Ru     101.0700
39     Sc      44.9559
40     Sr      87.6200
41     Ta     180.9480
42     Tb     158.9300
43     Tc      98.0000
44     Th     232.0381
45     Ti      47.8670
46     Tl     204.3800
47      V      50.9415
48      W     183.8400
49     Xe     131.2930
50      Y      88.9100
51     Zr      91.2200

Double brackets: outer `[]` selects from `data`, inner `[]` is a `list` of names. Leave off the inner brackets:

In [15]:
# EXPECTED-ERROR: this cell fails on purpose -- see the surrounding text
data['Symbol', 'Atomic Mass']

KeyError: ('Symbol', 'Atomic Mass')

`pandas` looked for one column literally named `('Symbol', 'Atomic Mass')` — the tabular cousin of last lecture's `KeyError`.

Single bracket + name → `Series`. Double bracket + list → `DataFrame`.

In [16]:
print(data['Atomic Mass'].mean())
print(data['Atomic Mass'].std())
print(data['Atomic Mass'].median())

107.07662499999999
65.30274887227671
99.535

Same `.mean()` as `np.mean(data['Atomic Mass'].values)` — a `Series` carries NumPy's methods along:

In [17]:
import numpy as np
print(np.mean(data['Atomic Mass'].values))

107.07662499999999

### [Check your understanding]

In the code cell below:
* Select the `'Vacancy Formation Energy (eV)'` and `'Cohesive Energy (eV)'` columns together as a two-column `DataFrame`
* Print the mean of just the `'Vacancy Formation Energy (eV)'` column

# `.describe()` — the victory lap

*Every column's mean, median, std — one method call away. Why not all of them, all columns, at once?*

In [18]:
data.describe()

,Bulk Static Energy (eV),Reference Energy (eV),Clean Cohesive,Cohesive Energy (eV),Cohesive Energy Per Atom (eV),Atomic Number,Mendeleev Number,Atomic Mass,Vacancy Formation Energy (eV),"Vacancy Migration Energy, non-disp (eV)","Vacancy Migration Energy, disp (eV)",Experimental Hvac,Experimental Hmig,Activation Energy (eV),NEBimageVolume,Ionization Energies (eV)
count,42.000000,42.000000,46.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,31.000000,11.000000,10.000000,52.000000,52.000000,52.000000
mean,-564.091404,-1.198810,0.869565,351.092885,3.250862,44.711538,46.076923,107.076625,1.140267,0.614324,0.887342,1.152727,0.933000,1.754590,2251.201538,7.904554
std,364.383783,1.346825,0.340503,283.901902,2.628718,25.114121,26.717730,65.302749,0.868211,0.659001,0.680440,0.457473,0.293449,1.365523,2078.335980,3.725197
min,-1331.898600,-5.320000,0.000000,0.000000,0.000000,2.000000,1.000000,4.002600,-0.062697,-0.353800,0.015024,0.450000,0.590000,-0.037017,0.000000,4.177128
25%,-837.900490,-2.115000,1.000000,55.647500,0.515236,24.500000,21.250000,53.938875,0.362718,0.117853,0.461670,0.785000,0.705000,0.520215,1109.940000,5.995918
50%,-511.200410,-0.490000,1.000000,377.435000,3.494771,43.500000,53.000000,99.535000,1.109312,0.489490,0.706770,1.290000,0.875000,1.656359,1782.645000,7.320250
75%,-296.937943,-0.250000,1.000000,583.777500,5.405363,67.250000,68.250000,165.512500,1.774330,0.764657,1.204430,1.400000,1.190000,2.484473,3047.427500,7.900173
max,-1.212876,0.000000,1.000000,902.990000,8.361009,90.000000,84.000000,232.038100,2.941206,2.729400,2.729400,1.850000,1.370000,5.477472,9807.000000,24.587387

`count`, `mean`, `std`, `min`, `25%`/`50%`/`75%` (percentiles — `50%` is the median), `max` — for every numeric column.

Every row is something you already know how to compute by hand. `.describe()` automates Lectures 4-5, nothing new numerically.

One column at a time, same scale:

In [19]:
data['Cohesive Energy (eV)'].describe()

count     52.000000
mean     351.092885
std      283.901902
min        0.000000
25%       55.647500
50%      377.435000
75%      583.777500
max      902.990000
Name: Cohesive Energy (eV), dtype: float64

For a text column instead — `.value_counts()` tallies rows per category:

In [20]:
data['STP Phase'].value_counts()

STP Phase
solid    47
gas       5
Name: count, dtype: int64

`.describe()` summarizes numbers; `.value_counts()` summarizes categories.

A picture, no Matplotlib required — `.style.bar()`:

In [21]:
data[['Symbol', 'Atomic Mass']].head(10).style.bar(subset=['Atomic Mass'], color='#5fba7d')

# Selecting rows: `.loc` and `.iloc`

* **`.iloc`** — by integer **position** (like list indexing)
* **`.loc`** — by **label** (whatever the index says)

In [22]:
data.iloc[0]

Symbol                                            Ac
Bulk Static Energy (eV)                   -442.22819
Reference Energy (eV)                          -0.25
Clean Cohesive                                   1.0
Cohesive Energy (eV)                          415.09
Cohesive Energy Per Atom (eV)               3.843385
Atomic Number                                     89
Mendeleev Number                                  48
Atomic Mass                                    227.0
STP Phase                                      solid
Natural Crystal Structure                        fcc
Vacancy Formation Energy (eV)               1.259565
Vacancy Migration Energy, non-disp (eV)       0.4603
Vacancy Migration Energy, disp (eV)          0.45434
Experimental Hvac                                NaN
Experimental Hmig                                NaN
Activation Energy (eV)                      1.719865
NEBimageVolume                                4900.0
Ionization Energies (eV)                        5.17
Name: 0, dtype: object

First row *by position* — columns of the table become the *index* of this new `Series`.

Slicing, same as `arrays`/`lists`:

In [23]:
data.iloc[0:3]

,Symbol,Bulk Static Energy (eV),Reference Energy (eV),Clean Cohesive,Cohesive Energy (eV),Cohesive Energy Per Atom (eV),Atomic Number,Mendeleev Number,Atomic Mass,STP Phase,Natural Crystal Structure,Vacancy Formation Energy (eV),"Vacancy Migration Energy, non-disp (eV)","Vacancy Migration Energy, disp (eV)",Experimental Hvac,Experimental Hmig,Activation Energy (eV),NEBimageVolume,Ionization Energies (eV)
0,Ac,-442.22819,-0.25,1.0,415.09,3.843385,89,48,227.0000,solid,fcc,1.259565,0.46030,0.45434,NaN,NaN,1.719865,4900.00,5.170000
1,Ag,-305.97104,-0.35,1.0,268.38,2.485000,47,71,107.8600,solid,fcc,0.683455,0.69518,0.69503,1.12,0.60,1.378635,1930.00,7.576230
2,Al,-403.99324,-0.23,1.0,379.35,3.512481,13,80,26.9815,solid,fcc,0.607072,0.58135,0.58165,0.68,0.68,1.188422,1779.29,5.985768

Compare `.loc`:

In [24]:
data.loc[0]

Symbol                                            Ac
Bulk Static Energy (eV)                   -442.22819
Reference Energy (eV)                          -0.25
Clean Cohesive                                   1.0
Cohesive Energy (eV)                          415.09
Cohesive Energy Per Atom (eV)               3.843385
Atomic Number                                     89
Mendeleev Number                                  48
Atomic Mass                                    227.0
STP Phase                                      solid
Natural Crystal Structure                        fcc
Vacancy Formation Energy (eV)               1.259565
Vacancy Migration Energy, non-disp (eV)       0.4603
Vacancy Migration Energy, disp (eV)          0.45434
Experimental Hvac                                NaN
Experimental Hmig                                NaN
Activation Energy (eV)                      1.719865
NEBimageVolume                                4900.0
Ionization Energies (eV)                        5.17
Name: 0, dtype: object

Looks identical to `.iloc[0]` right now — `data.index` is currently `0, 1, ..., 51`, so position and label coincide. Relabel the index or filter rows later, and they diverge.

Row + column together:

In [25]:
print(data.loc[0, 'Atomic Mass'])
print(data.iloc[0, 8])

227.0
227.0

Same value — `.loc` by row label + column *name*, `.iloc` by row position + column *position*.

*Look up iron by name, not row number?* Neither `.loc` nor `.iloc` alone gets you there — that's **logical (boolean) indexing**, coming in a few lectures.

> **Read more:** [PDSH — Data Indexing and Selection](https://jakevdp.github.io/PythonDataScienceHandbook/03.02-data-indexing-and-selection.html)

### [Check your understanding]

In the code cell below:
* Use `.iloc` to select the last row of `data` (hint: negative indices work just like they do for `lists`)
* Use `.loc` to print the `'Natural Crystal Structure'` of the element in row 0

Next time: `.describe()`'s numbers become pictures — real plots on this same table.

## Further reading

- [VanderPlas: Introducing Pandas objects](https://jakevdp.github.io/PythonDataScienceHandbook/03.01-introducing-pandas-objects.html)
- [VanderPlas: Data indexing and selection](https://jakevdp.github.io/PythonDataScienceHandbook/03.02-data-indexing-and-selection.html)
- [McKinney: Getting started with pandas](https://wesmckinney.com/book/pandas-basics)
- [Software Carpentry: Reading tabular data](https://swcarpentry.github.io/python-novice-gapminder/07-reading-tabular.html)